version: '2.1'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    mem_limit: 512M
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/snippets:/etc/nginx/snippets
    links:
      - sudobot_webhooks
    depends_on:
      - sudobot_webhooks

  sudobot_webhooks:
    build: ./webhooks
    container_name: sudobot_webhooks
    mem_limit: 512M
    ports:
      - 8080:8080
    volumes:
      - ./webhooks:/var/www/sudobot

  sudobot_service:
    build: ./service
    container_name: sudobot_service
    mem_limit: 512M
    volumes:
      - ./service:/usr/bin/sudobot
